SELECT C.CAR_ID, C.CAR_TYPE, 
ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID=H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND P.DURATION_TYPE='30일 이상'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;


# SELECT c.CAR_ID, c.CAR_TYPE,  
# round((c.daily_fee * 30 * (100-p.discount_rate)/100)) as FEE

# from CAR_RENTAL_COMPANY_CAR as c

# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as h ON C.CAR_ID=H.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p ON C.CAR_TYPE=P.CAR_TYPE

# where c.car_id not in 
#     (
#         select car_id
#         from CAR_RENTAL_COMPANY_CAR
#         WHERE END_DATE >= '2022-11-01'
#         AND START_DATE < '2022-12-01'
#     )
# and p.duration_type ='30일 이상'

# group by c.car_id
# having c.car_type in ('세단', 'SUV') and (FEE>=500000 AND FEE<2000000) 

# order by FEE desc, c.car_type, c.car_id desc
# ;